// 16x16 pixel-art bitmaps. Each row is 16 chars; '.' = transparent, letters index PALETTE.
// 'T' / 'U' are tint slots (item colour + its shade) filled at raster time.
export const PALETTE = {
  k: '#1b1427', // outline
  d: '#2b2b3a', // very dark
  w: '#fff6e5', // white
  l: '#e0e6eb', // light gray
  s: '#9aa5b1', // gray
  S: '#5c6b7a', // dark gray
  f: '#ffd9b3', // skin
  y: '#ffe08a', // pale yellow
  Y: '#ffd166', // yellow
  o: '#f77f00', // orange
  r: '#e63946', // red
  R: '#9d1d2a', // dark red
  p: '#f9a8d4', // pink
  P: '#d63384', // magenta
  v: '#8b5cf6', // violet
  V: '#4c1d95', // dark violet
  b: '#3a86ff', // blue
  B: '#1d3f8f', // dark blue
  c: '#7be0ff', // cyan
  C: '#a8dadc', // pale cyan
  g: '#57cc99', // green
  G: '#2d6a4f', // dark green
  n: '#8d5524', // brown
  N: '#5a3618', // dark brown
  t: '#c9a27e', // tan
};

// Palette overrides for recoloured variants: variant -> { letter: color }
export const VARIANTS = {
  big: { n: '#6b4a2b', t: '#a8845c', N: '#3f2a15' },
  night: { w: '#3b3b5c', b: '#8b5cf6', s: '#2b2b3a', l: '#4c1d95' },
  glass: { w: '#d6f6ff', b: '#7be0ff', s: '#a8dadc' },
  guard: { w: '#e63946', b: '#ffd166', s: '#9d1d2a' },
};

export const SPRITES = {
  // ------------------------------------------------------------------ player
  lumi_d: [
    '................',
    '.....kkkkkk.....',
    '....kbbbbbbk....',
    '...kbbbbbbbbk...',
    '...kbknnnnkbk...',
    '...kbkffffkbk...',
    '...kbkkffkkbk...',
    '...kbkffffkbk...',
    '....kkfrrfkk....',
    '....kbbbbbbk.kk.',
    '...kbbbbbbbbkkyk',
    '..kfkbbbbbbkkYyk',
    '....kbbbbbbk.kk.',
    '....kbbkkbbk....',
    '....kNNk.kNNk...',
    '....kkkk.kkkk...',
  ],
  lumi_u: [
    '................',
    '.....kkkkkk.....',
    '....kbbbbbbk....',
    '...kbbbbbbbbk...',
    '...kbbbbbbbbk...',
    '...kbbbbbbbbk...',
    '...kbbbbbbbbk...',
    '...kbbbbbbbbk...',
    '....kbbbbbbk....',
    '....kbbbbbbk.kk.',
    '...kbbbbbbbbkkyk',
    '..kfkbbbbbbkkYyk',
    '....kbbbbbbk.kk.',
    '....kbbkkbbk....',
    '....kNNk.kNNk...',
    '....kkkk.kkkk...',
  ],
  lumi_r: [
    '................',
    '.....kkkkkk.....',
    '....kbbbbbbk....',
    '...kbbbbbbbbk...',
    '...kbbbknnnkk...',
    '...kbbbkffffk...',
    '...kbbbkffkfk...',
    '...kbbbkffffk...',
    '....kkkkfrfk....',
    '....kbbbbbbk.kk.',
    '...kbbbbbbbbkkyk',
    '....kbbbbbfkkYyk',
    '....kbbbbbbk.kk.',
    '....kbbkkbbk....',
    '....kNNk.kNNk...',
    '....kkkk.kkkk...',
  ],

  // ---------------------------------------------------------------- monsters
  koropon: [
    '................',
    '................',
    '......kkkk......',
    '.....kppppk.....',
    '....kppwpppk....',
    '...kppwppppppk..',
    '..kpppppppppppk.',
    '..kpkpppppkpppk.',
    '..kpppppppppppk.',
    '..kppkkkkkppppk.',
    '..kpppppppppppk.',
    '...kPpppppppPk..',
    '....kPPPPPPPk...',
    '.....kkkkkkk....',
    '................',
    '................',
  ],
  patapata: [
    '................',
    '................',
    '................',
    '..kk........kk..',
    '.kwwk......kwwk.',
    '.kwwwkkkkkkwwwk.',
    '.kwwwwwwwwwwwwk.',
    '.kwtwwkwwkwwtwk.',
    '..kwwwwwwwwwwk..',
    '...kwwwkkwwwk...',
    '....kwwk.kwwk...',
    '.....kk...kk....',
    '................',
    '................',
    '................',
    '................',
  ],
  kurumi: [
    '................',
    '.......k........',
    '....k..k..k.....',
    '.....kkkkkk.....',
    '..k.knnnnnnk.k..',
    '...knnttttnnk...',
    '..knntkttktnnk..',
    '.kknnttttttnnkk.',
    '..knnnttttnnnk..',
    '..k.knnnnnnk.k..',
    '.....kNNNNk.....',
    '....k.kkkk.k....',
    '................',
    '................',
    '................',
    '................',
  ],
  rousoku: [
    '.......o........',
    '......oYo.......',
    '......oYYo......',
    '.....kYYYYk.....',
    '......kYYk......',
    '.......kk.......',
    '.....kwwwwk.....',
    '....kwwwwwwk....',
    '....kwkwwkwk....',
    '....kwwwwwwk....',
    '....kwwkkwwk....',
    '....kwwwwwwk....',
    '....kwwwwwwk....',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  kabocha: [
    '........gg......',
    '.......kggk.....',
    '....kkkkkkkkk...',
    '...kooooooooook.',
    '..kooYooooooYook',
    '..koYYYooooYYYok',
    '..kooooooooooook',
    '..kooYoYYYYoYook',
    '...kooYYYYYYook.',
    '....kooooooook..',
    '.....kkkkkkkk...',
    '....ktttttttk...',
    '...kttkttttkttk.',
    '....ktttttttk...',
    '.....kttkttk....',
    '.....kk..kk.....',
  ],
  kasasagi: [
    '................',
    '................',
    '......kkk.......',
    '.....kdddk......',
    '....kddcddkk....',
    '....kdddddkYk...',
    '...kddddddkkk...',
    '..kddwwwwddk....',
    '.kdddwwwwwddk...',
    '.kddddwwwwddk...',
    '..kdddddddddk...',
    '...kkddddddk....',
    '.....kkkkkk.....',
    '......kY.kY.....',
    '................',
    '................',
  ],
  ibara: [
    '..........k.....',
    '.......kkkgk....',
    '......kggggk....',
    '.....kgGgkk.....',
    '....kgGgk.k.....',
    '...kgGgk........',
    '..kgGgk.kk......',
    '..kgggk.kRRk....',
    '..kgGgk.kRrRk...',
    '...kgGgk.kRRk...',
    '....kgGgkkkk....',
    '.....kgGggk.....',
    '....k.kgGgk.....',
    '.....kgGGgk.....',
    '....kGGGGGGk....',
    '....kkkkkkkk....',
  ],
  kagami: [
    '................',
    '.....kkkkkk.....',
    '....kyyyyyyk....',
    '...kyCCCCCCyk...',
    '...kyCkCCkCyk...',
    '...kyCCCCCCyk...',
    '...kyCCkkCCyk...',
    '...kyCCCCCCyk...',
    '....kyyyyyyk....',
    '...kCCCCCCCCk...',
    '..kCCcCCCCcCCk..',
    '..kCCCCCCCCCCk..',
    '..kCCkCCkCCkCk..',
    '...kk.kk.kk.k...',
    '................',
    '................',
  ],
  yousei: [
    '................',
    '................',
    '.......kkk......',
    '..kk..kvvvk..kk.',
    '.kCCk.kvfvk.kCCk',
    '.kCCCkkfkfkkCCCk',
    '.kCCCCkfffkCCCCk',
    '..kCCCkvvvkCCCk.',
    '...kCkvvvvvkCk..',
    '....kkvvvvvkk...',
    '.....kvvvvvk....',
    '....kvvvvvvvk...',
    '....kkkkkkkkk...',
    '......kf.fk.....',
    '................',
    '................',
  ],
  teacup: [
    '................',
    '.....kkkkkk.....',
    '....kwwwwwwk....',
    '...kkkkkkkkkk...',
    '...kwwwwwwwwk...',
    '...kwkwwwwkwkk..',
    '...kwwwwwwwwk.k.',
    '...kbbbbbbbbk.k.',
    '...kwwbwwbwwkk..',
    '...kwwwwwwwwk...',
    '....kwwwwwwk....',
    '...kkkkkkkkkk...',
    '..kssssssssssk..',
    '...kkkkkkkkkk...',
    '....kk....kk....',
    '................',
  ],
  ningyou: [
    '................',
    '....kk....kk....',
    '...knnkkkknnk...',
    '...knknnnnknk...',
    '...kkkffffkkk...',
    '....kfkffkfk....',
    '....kffffffk....',
    '....kfkkkkfk....',
    '.....kffffk.....',
    '....kkppppkk....',
    '...kfkppppkfk...',
    '....kppppppk....',
    '...kppppppppk...',
    '...kkkkkkkkkk...',
    '....kn.....nk...',
    '................',
  ],
  karasu: [
    '................',
    '................',
    '....kkk.........',
    '...kdddk........',
    '..kddrddknnk....',
    '..kdddddknnnk...',
    '..kddddddkkk....',
    '.kddddddddk.....',
    '.kddnddddddk....',
    '.kdddddnddddk...',
    '..kddddddddddk..',
    '...kkddddddkkk..',
    '.....kkkkkk.....',
    '......kn.kn.....',
    '................',
    '................',
  ],
  pudding: [
    '..........o.....',
    '.........ok.....',
    '........k.......',
    '......kkkkk.....',
    '.....kNNNNNk....',
    '....kNNNNNNNk...',
    '...kNNNNNNNNNk..',
    '...kYNYYYYYNYk..',
    '..kYYkYYYYkYYYk.',
    '..kYYYYYYYYYYYk.',
    '..kYYYYkkkYYYYk.',
    '.kYYYYYYYYYYYYYk',
    '.kYYYYYYYYYYYYYk',
    '.kkkkkkkkkkkkkkk',
    '................',
    '................',
  ],
  wolf: [
    '................',
    '................',
    '..kk............',
    '.kCCk...........',
    '.kCCCkkkkkkk....',
    '.kCbCCCCCCCCk...',
    '.kCCCCCCCCCCCkk.',
    '..kCCwCCCCCCCCCk',
    '..kkCCCCCCCCCCk.',
    '....kCCCCCCCCk..',
    '....kCCkkkCCk...',
    '....kCk...kCk...',
    '....kk.....kk...',
    '................',
    '................',
    '................',
  ],
  neko: [
    '......kkk.......',
    '.....kVVVk......',
    '....kVVVVVk.....',
    '..kkkkvvvkkkkk..',
    '..kdk.....kdk...',
    '..kdddkkkkdddk..',
    '..kdYddddddYdk..',
    '..kdddddpdddddk.',
    '...kddkdddkddk..',
    '....kdddddddk...',
    '...kdddddddddk..',
    '...kddddddddddkk',
    '...kdddddddddk.k',
    '....kkkkkkkkk.k.',
    '.....kd.kd..kk..',
    '................',
  ],
  ryu: [
    '................',
    '....kk..........',
    '...kvvkkkk......',
    '..kvvvvvvvk.....',
    '..kvcvvvvvvk....',
    '..kvvvvkkkvk.kk.',
    '...kvvvvvvvkkVk.',
    '....kvyvvvvVVVk.',
    '...kvvvvyvvVVk..',
    '..kvvvvvvvvvvk..',
    '..kvvyvvvvvvvvk.',
    '..kvvvvvvvvvvvvk',
    '...kkvvvkkvvkkk.',
    '.....kkk..kk....',
    '................',
    '................',
  ],
  keeper: [
    '....kkkkkkk.....',
    '...kgggggggk....',
    '..kkkkkkkkkkk...',
    '...kfffffffk....',
    '...kfkfffkfk....',
    '...kfffffffk....',
    '...kfNNNNNfk....',
    '....kfffffk.....',
    '...kkrrrrrkk....',
    '..krrkwwwkrrk...',
    '.kfkrrkwwwkrrkfk',
    '.kkkrrkwwwkrrkkk',
    '...krrkwwwkrrk..',
    '...kkkkkkkkkkk..',
    '....kNNk.kNNk...',
    '....kkkk.kkkk...',
  ],
  g_pumpkin: [
    '...kYkkYkkYk....',
    '...kYYYYYYYk....',
    '..kkkkkkkkkkkk..',
    '.kooooooooooook.',
    'koorrrooooorrrok',
    'koorrroooooorrok',
    'kooooooooooooook',
    'koYYoYYYYYYoYYok',
    '.kooYYYYYYYYook.',
    '.kooooooooooook.',
    '..kooooooooook..',
    '...kkkkkkkkkk...',
    '..kVVVVVVVVVVk..',
    '..kVVkVVVVkVVk..',
    '...kkkkkkkkkk...',
    '................',
  ],
  g_thorn: [
    '....k.kk.kk.k...',
    '....kkkkkkkkk...',
    '....kGGGGGGGk...',
    '...kGGffffGGk...',
    '...kGfkffkfGk...',
    '...kGffffffGk...',
    '...kGGfrrfGGk...',
    '....kGGGGGGk....',
    '...kkgggggggkk..',
    '..kgggrgggggrgk.',
    '..kGgggggggggGk.',
    '..kGGgggggggGGk.',
    '.kGGGgggggggGGGk',
    '.kGGGGgggggGGGGk',
    '.kGGGGGGGGGGGGGk',
    '.kkkkkkkkkkkkkkk',
  ],
  g_mirror: [
    '.......kk.......',
    '......kVVk......',
    '.....kVVVVk.....',
    '....kVVVVVVk....',
    '..kkkkvvvvkkkk..',
    '....kddddddk....',
    '....kdcddcdk.kk.',
    '....kddddddk.kyk',
    '.....kVVVVkfkyCk',
    '....kVVVVVVkkkyk',
    '....kVVVVVVk..k.',
    '...kVVVVVVVVk...',
    '...kVVkVVkVVk...',
    '..kVVVVVVVVVVk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],

  // ------------------------------------------------------------------- items
  weapon: [
    '..........kk....',
    '.........kTTk...',
    '........kTUTk...',
    '.......kTUTk....',
    '......kTUTk.....',
    '.....kTUTk......',
    '....kTUTk.......',
    '..kkkTUTk.......',
    '.kYYYkTk........',
    '..kkkYkkk.......',
    '....kNkYk.......',
    '...kNk..k.......',
    '..kkk...........',
    '................',
    '................',
    '................',
  ],
  shield: [
    '................',
    '.....kkkkkk.....',
    '....kTTTTTTk....',
    '...kTTTTTTTTk...',
    '..kTTTUUUUTTTk..',
    '..kTTUUYYUUTTk..',
    '..kTTUYYYYUTTk..',
    '..kTTUYYYYUTTk..',
    '..kTTUUYYUUTTk..',
    '..kTTTUUUUTTTk..',
    '...kTTTTTTTTk...',
    '....kTTTTTTk....',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
  ],
  arrow: [
    '................',
    '............kk..',
    '...........klk..',
    '..........klk...',
    '.........kTk....',
    '........kTk.....',
    '.......kTk......',
    '......kTk.......',
    '.....kTk........',
    '..k.kTk.........',
    '.krkTk..........',
    '.krrk...........',
    '..kkk...........',
    '................',
    '................',
    '................',
  ],
  herb: [
    '................',
    '........kk......',
    '.......kggk.....',
    '......kgk.k.....',
    '.....kkkkk......',
    '....kTTTTTk.....',
    '...kTwTTTTTk....',
    '...kTTTTTTTk....',
    '...kTTTTTTTk....',
    '...kUTTTTTUk....',
    '....kUUUUUk.....',
    '.....kkkkk......',
    '................',
    '................',
    '................',
    '................',
  ],
  herb2: [
    '................',
    '.......k........',
    '......kTk.......',
    '......kTk.......',
    '.....kTTTk......',
    '.....kTTTk......',
    '....kTwTTTk.....',
    '....kTTTTTk.....',
    '...kTTTTTTTk....',
    '...kTTTTTTTk....',
    '...kUTTTTTUk....',
    '....kUUUUUk.....',
    '.....kkkkk......',
    '................',
    '................',
    '................',
  ],
  herb3: [
    '................',
    '.......kk.......',
    '......kNNk......',
    '....kkNNNNkk....',
    '...kNNNNNNNNk...',
    '...kkkkkkkkkk...',
    '...kTTTwTTTTk...',
    '...kTTTTTTTTk...',
    '....kTTTTTTk....',
    '....kTTTTTTk....',
    '.....kUTTUk.....',
    '......kkkk......',
    '................',
    '................',
    '................',
    '................',
  ],
  scroll: [
    '................',
    '....kkkkkkkk....',
    '...kwwwwwwwwkk..',
    '...kwssswwwwkwk.',
    '...kwwwwwwwwkkk.',
    '...kwsssssswwwk.',
    '...kwwwwwwwwwwk.',
    '...kwssssswwwwk.',
    '...kwwwwwwwwwwk.',
    '...kwssssssswwk.',
    '...kwwwwTTwwwwk.',
    '...kwwwTTTTwwwk.',
    '...kwwwwTTwwwwk.',
    '...kkkkkkkkkkkk.',
    '................',
    '................',
  ],
  staff: [
    '............kk..',
    '..........kkTTk.',
    '..........kTTTk.',
    '...........kTk..',
    '..........knk...',
    '.........knk....',
    '........knk.....',
    '.......knk......',
    '......knk.......',
    '.....knk........',
    '....knk.........',
    '...knk..........',
    '..kkk...........',
    '................',
    '................',
    '................',
  ],
  gold: [
    '................',
    '................',
    '................',
    '................',
    '......kkkk......',
    '.....kYyYYk.....',
    '..kkkkYYYYkkkk..',
    '.kYyYYkkkkYyYYk.',
    '.kYYYYYkkYYYYYk.',
    '.koYYYYkkYYYYok.',
    '..kooookkooookk.',
    '...kkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
  ],
  trap: [
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kSSSSSSSSSSSSk.',
    '.kSTSSSTTSSSTSk.',
    '.kSSTSSTTSSTSSk.',
    '.kSSSTTTTTTSSSk.',
    '.kSSTSSTTSSTSSk.',
    '.kSTSSSTTSSSTSk.',
    '.kSSSSSSSSSSSSk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
  ],
  stairs: [
    'kkkkkkkkkkkkkkkk',
    'kddddddddddddddk',
    'kdssssssssssssdk',
    'kdSSSSSSSSSSSSdk',
    'kddssssssssssddk',
    'kddSSSSSSSSSSddk',
    'kdddssssssssdddk',
    'kdddSSSSSSSSdddk',
    'kddddssssssddddk',
    'kddddSSSSSSddddk',
    'kdddddssssdddddk',
    'kdddddSSSSdddddk',
    'kddddddssddddddk',
    'kddddddddddddddk',
    'kddddddddddddddk',
    'kkkkkkkkkkkkkkkk',
  ],
};

/** Throws when any bitmap is malformed. Used by tests. */
export function validateSprites() {
  const letters = new Set([...Object.keys(PALETTE), 'T', 'U', '.']);
  for (const [name, rows] of Object.entries(SPRITES)) {
    if (rows.length !== 16) throw new Error(`sprite ${name}: ${rows.length} rows`);
    rows.forEach((row, i) => {
      if (row.length !== 16) throw new Error(`sprite ${name} row ${i}: length ${row.length}`);
      for (const ch of row) if (!letters.has(ch)) throw new Error(`sprite ${name} row ${i}: bad letter ${ch}`);
    });
  }
  return true;
}
